Algoritmo "semnome"
// Disciplina   : Lógica de Programação
// Professor   : Jailson
// Descrição   :
// Autor(a)    : Luiz Felipe
// Data atual  : 06/09/2023
Var
   numero:inteiro

Inicio
   enquanto numero <= 0 faça
      Escreval("Digite um valo inteiro maior que zero:")
      Leia(numero)
   fimenquanto

   para numero de 1 ate numero passo 1 faça
      Escreva(numero,",")
   fimpara

Fimalgoritmo