Algoritmo "semnome"
// Disciplina   : Lógica de Programação
// Professor   : Jailson
// Descrição   :
// Autor(a)    : Luiz Felipe
// Data atual  : 06/09/2023
Var

   numero, tabuada:inteiro

Inicio
   Escreval("Digite o valor para ter sua tabuada correspondente")
   Leia(tabuada)

   para numero de 1 ate 10 passo 1 faça
      Escreval(numero," X",tabuada,"=", numero*tabuada)
   fimpara

Fimalgoritmo